//! `hopper-proto` — protobuf wire types for the swarm.
//!
//! The messages from CLAUDE.md's wire-protocol table, generated from
//! `proto/hopper.proto` by prost (see `build.rs`). The only inter-node payload is
//! the [`Activation`] (Invariant 1); the KV cache is never represented here.
//!
//! Phase 3 actively uses [`ActivationStream`] (request) + [`StageResponse`]
//! (response) over libp2p request-response. The remaining types (`AuditChallenge`,
//! `AuditReveal`, `FraudProof`, `TokenPublish`, `InferenceRequest`) are defined for
//! the full protocol; `FraudProof`/gossip wiring lands with peer-relay.

// Generated by prost into OUT_DIR for the `hopper` package.
include!(concat!(env!("OUT_DIR"), "/hopper.rs"));

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;

    #[test]
    fn activation_round_trips_through_protobuf() {
        let act = Activation {
            n_tokens: 2,
            d_model: 3,
            data: vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
        };
        let bytes = act.encode_to_vec();
        let back = Activation::decode(bytes.as_slice()).unwrap();
        assert_eq!(act, back);
    }

    #[test]
    fn activation_stream_oneof_round_trips() {
        let msg = ActivationStream {
            session: "s".into(),
            stage_id: 1,
            seq_pos: 7,
            input: Some(activation_stream::Input::Ids(TokenIds {
                ids: vec![104, 105],
            })),
        };
        let back = ActivationStream::decode(msg.encode_to_vec().as_slice()).unwrap();
        assert_eq!(msg, back);
    }
}
